### PR TITLE
fix linker error involving frobby_version

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by d-torrance** [comment]
If this is merged and everything works nicely, could we get a new v0.9.5 tag, too?

**Comment by mahrud** [comment]
@DanGrayson

**Comment by mahrud** [comment]
@d-torrance actually, since the last tag was 0.9.1, perhaps I should change to 0.9.2. There's no reason to jump up when the only changes have been dealing with the version!

**Comment by mahrud** [comment]
Ehh, since the M2 pull request is already merged, let's just leave it as 0.9.5. Hopefully the confusion will be minimal.

**Comment by d-torrance** [comment]
IIRC, the version bump came from merging the CoCoA patches -- they'd bumped the version up to 0.9.4.  (I assume they had a 0.9.2 and 0.9.3 at some point?)

**Comment by mahrud** [comment]
Ah, okay. This is fine then.

**Pull request merged**
